Recomendaciones/RSMovieLens/urls.py
#encoding:utf-8

from django.urls import path
from django.contrib import admin
from main import views

urlpatterns = [
    path('', views.index),
    path('populate', views.populateDB),
    path('loadRS', views.loadRS),
    path('search', views.search),
    path('recommendedFilms', views.recommendedFilms),
    path('similarFilms', views.similarFilms),
    path('admin/', admin.site.urls),
]



Recomendaciones/main/models.py
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator,URLValidator


class Occupation(models.Model):
    occupationName = models.CharField(max_length=30)
    def __str__(self):
        return self.occupationName
 
    
class Genre(models.Model):
    genreName = models.CharField(max_length=20) 
    def __str__(self):
        return self.genreName   
    
      
class UserInformation(models.Model):
    age = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)])
    gender = models.CharField(max_length=1, choices=(('F', 'Female'),('M','Male'),))
    occupation = models.ForeignKey(Occupation, on_delete=models.DO_NOTHING)
    zipCode = models.CharField(max_length=8)
    def __str__(self):
        return self.gender+" "+self.zipCode
  
    
class Film(models.Model):
    movieTitle = models.CharField(max_length=100)
    releaseDate = models.DateField(null=True, blank=True)
    releaseVideoDate = models.DateField(null=True, blank=True)
    IMDbURL = models.URLField(validators=[URLValidator()])
    genres = models.ManyToManyField(Genre)
    ratings = models.ManyToManyField(UserInformation, through="Rating")
    def __str__(self):
        return self.movieTitle

    
class Rating(models.Model):
    user = models.ForeignKey(UserInformation, on_delete=models.CASCADE)
    film = models.ForeignKey(Film, on_delete=models.CASCADE)
    rateDate = models.DateField(null=True, blank=True)
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    def __str__(self):
        return str(self.rating)

Recomendaciones/main/forms.py
# -*- encoding: utf-8 -*-
from django import forms

class UserForm(forms.Form):
    id = forms.CharField(label='User ID')
    
class FilmForm(forms.Form):
    id = forms.CharField(label='Movie ID')

Recomendaciones/main/views.py
import shelve
from main.models import UserInformation, Film, Rating
from main.forms import UserForm, FilmForm
from django.shortcuts import render, get_object_or_404
from main.recommendations import  transformPrefs, calculateSimilarItems, getRecommendedItems, topMatches
from main.populate import populateDatabase



# Funcion que carga en el diccionario Prefs todas las puntuaciones de usuarios a peliculas. Tambien carga el diccionario inverso y la matriz de similitud entre items
# Serializa los resultados en dataRS.dat
def loadDict():
    Prefs={}   # matriz de usuarios y puntuaciones a cada a items
    shelf = shelve.open("dataRS.dat")
    ratings = Rating.objects.all()
    for ra in ratings:
        user = int(ra.user.id)
        itemid = int(ra.film.id)
        rating = float(ra.rating)
        Prefs.setdefault(user, {})
        Prefs[user][itemid] = rating
    shelf['Prefs']=Prefs
    shelf['ItemsPrefs']=transformPrefs(Prefs)
    shelf['SimItems']=calculateSimilarItems(Prefs, n=10)
    shelf.close()
    


    
#  CONJUNTO DE VISTAS

def index(request): 
    return render(request,'index.html')

def populateDB(request):
    populateDatabase() 
    return render(request,'populate.html')

def loadRS(request):
    loadDict()
    return render(request,'loadRS.html')
 
#APARTADO A
def search(request):
    if request.method=='GET':
        form = UserForm(request.GET, request.FILES)
        if form.is_valid():
            idUser = form.cleaned_data['id']
            user = get_object_or_404(UserInformation, pk=idUser)
            return render(request,'ratedFilms.html', {'usuario':user})
    form=UserForm()
    return render(request,'search_user.html', {'form':form })

# APARTADO B
def recommendedFilms(request):
    if request.method=='GET':
        form = UserForm(request.GET, request.FILES)
        if form.is_valid():
            idUser = form.cleaned_data['id']
            user = get_object_or_404(UserInformation, pk=idUser)
            shelf = shelve.open("dataRS.dat")
            Prefs = shelf['Prefs']
            SimItems = shelf['SimItems']
            shelf.close()
            rankings = getRecommendedItems(Prefs, SimItems, int(idUser))
            recommended = rankings[:2]
            items = []
            for re in recommended:
                item = Film.objects.get(pk=re[1])
                items.append(item)
            return render(request,'recommendationItems.html', {'user': user, 'items': items})
    form = UserForm()
    return render(request,'search_user.html', {'form': form})

# APARTADO C
def similarFilms(request):
    film = None
    if request.method=='GET':
        form = FilmForm(request.GET, request.FILES)
        if form.is_valid():
            idFilm = form.cleaned_data['id']
            film = get_object_or_404(Film, pk=idFilm)
            shelf = shelve.open("dataRS.dat")
            ItemsPrefs = shelf['ItemsPrefs']
            shelf.close()
            recommended = topMatches(ItemsPrefs, int(idFilm),n=3)
            items=[]
            for re in recommended:
                item = Film.objects.get(pk=int(re[1]))
                items.append(item)
            return render(request,'similarFilms.html', {'film': film,'films': items})
    form = FilmForm()
    return render(request,'search_film.html', {'form': form})


Recomendaciones/main/templates/header.html
<header>
<nav>
	<ul>
		<li><a href="/">Home</a></li>
		<li><a href="/populate">Populate database</a></li>
		<li><a href="/loadRS">Load Recommender System data</a></li>
		<li><a href="/search">Search movies rated by a user</a></li>
		<li><a href="/recommendedFilms">Recommend two movies to a user</a></li>
		<li><a href="/similarFilms">Three films more like other</a></li>
	</ul>
</nav>
</header>

Recomendaciones/main/templates/index.html
<html>
<head>
<title>Recommender System Movielens</title>
</head>
<body>
{% include 'header.html' %}
<h1>Welcome to Recommender System for MovieLens!!!</h1>
</body>
</html>

Recomendaciones/main/templates/loadRS.html
<html>
<head>
<title>Recommender System Movielens</title>
</head>
<body>
{% include 'header.html' %}
<h1>Data loaded for the recommendation system</h1>
</body>
</html>

Recomendaciones/main/templates/populate.html
<html>
<head>
<title>Recommender System Movielens</title>
</head>
<body>
{% include 'header.html' %}
<h1>Database loaded</h1>
</body>
</html>

Recomendaciones/main/templates/ratedFilms.html
<html>
<head>
<title>Recommender System Movielens</title>
</head>
<body>
{% include 'header.html' %}
<section>
<h1>Movies and ratings for userid {{usuario.id}}</h1>
{% for rating in usuario.rating_set.all %}
<ul>Movie: {{rating.film.movieTitle}} - Rating: {{rating.rating}}</ul><br/>
{% empty %}
<h2> User has not rated any movie </h2>
{% endfor %}
</section>
</body>
</html>

Recomendaciones/main/templates/recommendationItems.html
<html>
<head>
<title>Recommender System Movielens</title>
</head>
<body>
{% include 'header.html' %}
<h1>Recommended movies for the UserID: {{user.id}}</h1>
{% for item in items %}
<ul>
<li>Title: {{item.movieTitle}}</li>
</ul>
{% empty %}
<h2> Insufficient user data </h2>
{% endfor %}
</body>
</html>

Recomendaciones/main/templates/search_film.html
<html>
<head>
<title>Recommender System Movielens</title>
</head>
<body>
<header>
{% include 'header.html' %}

<h1>Search movie</h1>
<form id='form' method='get' action=''>
{{form.as_p}}
<p><input type='submit' value='Confirm'/></p>
</form>

</body>
</html>

Recomendaciones/main/templates/search_user.html
<html>
<head>
<title>Recommender System Movielens</title>
</head>
<body>
<header>
{% include 'header.html' %}

<h1>Search user</h1>
<form id='form' method='get' action=''>
{{form.as_p}}
<p><input type='submit' value='Confirm'/></p>
</form>

</body>
</html>

Recomendaciones/main/templates/similarFilms.html
<html>
<head>
<title>Recommender System Movielens</title>
</head>
<body>
{% include 'header.html' %}
<section>
<h1>Three movies more like to {{film.movieTitle}} are:</h1>
<l>
{% for f in films %}
<li>{{f.movieTitle}}</li>
{% endfor %}
</l>
</section>
</body>
</html>