Licoreando/Licoreando/urls.py
#encoding:utf-8
from django.contrib import admin
from django.urls import path

from licor import views as lview
from usuario import views as uview


urlpatterns = [
    path('', lview.index),
    path('admin/', admin.site.urls),
    path('licor/search', lview.buscarLicor),
    path('user/register', uview.registro),
    path('user/login', uview.loginUsuario),
    path('user/logout', uview.logoutUsuario),
    path('user/forms', uview.formularios),
    path('user/recomendation', uview.recomendaciones)
]




Licoreando/licor/models.py
from django.db import models

class Licor(models.Model):
    id = models.AutoField(primary_key=True)
    codigoReferencia = models.TextField(blank=True,null=True)
    titulo = models.TextField(blank=True,null=True)
    descripcion = models.TextField(blank=True,null=True)
    precio = models.FloatField(blank=True,null=True)
    origen = models.TextField(blank=True,null=True)
    cantidad = models.TextField(blank=True,null=True) #Volumen o peso
    graduacion = models.FloatField(blank=True,null=True)
    urlProducto = models.URLField(unique=True)
    urlImagen = models.URLField(blank=True,null=True)
    enStock = models.BooleanField()
   
class Categoria(models.Model):
    nombre = models.TextField(unique=True)
    licor = models.ManyToManyField(Licor, blank=True)
    

Licoreando/licor/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.template.defaultfilters import default

from licor.models import Categoria


class SearchForm(forms.Form):
    busqueda = forms.CharField(required=False,label="Búsqueda")
    graduacionMinima = forms.FloatField(required=False,label="Graduación mínima",min_value=0,max_value=99)
    graduacionMaxima = forms.FloatField(required=False,label="Graduación máxima",min_value=0,max_value=99)
    precioMinimo = forms.FloatField(required=False,label="Precio mínimo",min_value=0,max_value=9999)
    precioMaximo = forms.FloatField(required=False,label="Precio máximo",min_value=0,max_value=9999)
    ordenarSimilitud = forms.RadioSelect()
    ordenarPrecio = forms.RadioSelect()
    ordenarTitulo = forms.RadioSelect()
    ordenarGraduacion = forms.RadioSelect()
    ordenarProcedencia = forms.RadioSelect()
    def clean(self):
        cleaned_data = super().clean()
        graduacionMinima = cleaned_data.get('Graduación mínima')
        graduacionMaxima = cleaned_data.get('Graduación máxima')
        precioMinimo = cleaned_data.get('Precio mínima')
        precioMaximo = cleaned_data.get('Precio máxima')
        nombre = cleaned_data.get('Categoría')
        try:
            if graduacionMinima > graduacionMaxima:
                raise forms.ValidationError(
                    _("La graduación mínima no puede ser superior a la graduación máxima"),
                    code='invalid'
                )
            if precioMinimo > precioMaximo:
                raise forms.ValidationError(
                    _("El precio mínimo no puede ser superior al precio máximo"),
                    code='invalid'
                )
        except:
            pass

Licoreando/licor/views.py
from django.shortcuts import render
from django.template.defaultfilters import lower

from licor.forms import SearchForm
from licor.models import Licor, Categoria
from whooshLicor.utils import listarPorAtributo

def index(request): 
    return render(request,'index.html')

def buscarLicor(request):
    form=SearchForm()
    categorias = Categoria.objects.all().order_by('nombre')
    if request.method=='POST':
        form = SearchForm(request.POST, request.FILES)
        if form.is_valid():
            busqueda = form.cleaned_data["busqueda"]
            graduacionMinima = form.cleaned_data["graduacionMinima"]
            graduacionMaxima = form.cleaned_data["graduacionMaxima"]
            precioMinimo = form.cleaned_data["precioMinimo"]
            precioMaximo = form.cleaned_data["precioMaximo"]
            elem = request.POST["elem"]
            page = request.POST["page"]
            groupDic={}
            if precioMinimo and precioMaximo:
                groupDic["precio"]=(precioMinimo,precioMaximo)
            if graduacionMinima and graduacionMaxima:
                groupDic["graduacion"]=(graduacionMinima,graduacionMaxima)
            orden = request.POST["order"]
            categoriaP = request.POST.getlist("categoria")
            categoria = []
            for cat in categoriaP:
                categoria.append((Categoria.objects.get(id=cat)).nombre.lower())
            busqueda = lower(busqueda)       
            licoresId = listarPorAtributo(busqueda=busqueda,categoria=categoria, order =orden,groupDic=groupDic, nElementosPagina=int(elem), pagina=int(page))
            licores = getLicores(licoresId)
            return render(request,'search_licor.html', {'licores':licores,'form':form ,'categorias': categorias,'elem':elem,'page':page})
    licoresId = listarPorAtributo()
    licores = getLicores(licoresId)
    return render(request,'search_licor.html', {'form':form,'licores':licores, 'categorias': categorias,'elem':20,'page':1})

def getLicores(licoresId):
    licores = []
    for licor in licoresId[0]:
        licores.append(Licor.objects.get(id=licor)) 
    return licores

Licoreando/licor/templates/header.html
<meta charset="UTF-8">
<style>
  body {
    background-image: url("https://raw.githubusercontent.com/Iriabow/aii/master/Licoreando/static/bodega1.jpg");
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
    font-size: 13pt;
    font-family: sans-serif;
  }

  .index {
    background-image: url("https://raw.githubusercontent.com/Iriabow/aii/master/Licoreando/static/bodega3.jpg");
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
    font-size: 13pt;
    font-family: sans-serif;
  }

  ul.menu {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
  }

  .center {
    margin: auto;
    width: 20%;
    padding: 10px;
    background-color: #FAD887;
  }

  li.menu_option {
    float: left;
  }

  li a.option {
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
  }

  li a.option:hover {
    background-color: #111;
  }

  .active {
    background-color: red;
  }

  .error {
    color: red;
  }

  .preferencias_left {
    display: block;
    display: inline-block;
    float: left;
    margin: 5px
  }

  .preferencias_center {
    display: block;
    display: inline-block;
    float: left;
    margin: 5px
  }

  .preferencias_right {
    display: block;
    display: inline-block;
    float: left;
    margin: 5px
  }

  .search {
    background-color: #FAD887;
    display: inline-block;
    float: left;
    margin: 5px
  }

  .image_search {
    float: right;
  }

  table,
  td,
  th {
    border: 1px solid black;
    text-align: center;
    word-wrap: break-word;
    margin: 5px;
    font-size: 13pt;
  }

  .search,
  .center,
  table {
    background-image: url("https://raw.githubusercontent.com/Iriabow/aii/master/Licoreando/static/tabla2.jpg");
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
  }

  .description {
    color: blue;
  }

  .tooltip {
    position: relative;
    display: inline-block;
    border-bottom: 1px dotted black;
  }

  .tooltip .tooltiptext {
    visibility: hidden;
    width: 600px;
    background-color: #555;
    color: #fff;
    text-align: center;
    border-radius: 6px;
    padding: 5px 0;
    position: absolute;
    z-index: 1;
    bottom: 125%;
    left: 50%;
    margin-left: -60px;
    opacity: 0;
    transition: opacity 0.3s;
  }

  .tooltip .tooltiptext::after {
    content: "";
    position: absolute;
    top: 100%;
    left: 50%;
    margin-left: -5px;
    border-width: 5px;
    border-style: solid;
    border-color: #555 transparent transparent transparent;
  }

  .tooltip:hover .tooltiptext {
    visibility: visible;
    opacity: 1;
  }

  .green {
    color: green;
  }

  .red {
    color: red;
  }

  .titulo {
    text-align: center;
    color: white;
    background-color: maroon;
    display: block;

  }
  .banner{
  background-color: maroon;
  }
  .bannerImg{
    display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
  }
</style>
<header>
  {% if request.path != '/' %}
  <div class="banner"><img class="bannerImg" src="https://raw.githubusercontent.com/Iriabow/aii/master/Licoreando/static/search.jpg" /></div>
  {%endif%}
  <nav>
    <ul class="menu">
      <li class="menu_option"><a class="option" href="/">Home</a></li>
      <li class="menu_option"><a class="option" href="/licor/search">Licores</a></li>
      {% if not user.is_authenticated %}
      <li class="menu_option"><a class="option" href="/user/register">Registro</a></li>
      <li class="menu_option"><a class="option" href="/user/login">Login</a></li>
      {%endif%}
      {% if user.is_authenticated %}
      <li class="menu_option"><a class="option" href="/user/forms">Formulario</a></li>
      <li class="menu_option"><a class="option" href="/user/recomendation">Recomendación</a></li>
      <li class="menu_option"><a class="option" href="/user/logout">Logout</a></li>
      {%endif%}
    </ul>
  </nav>
</header>

Licoreando/licor/templates/index.html
<html>
<head>
<title>Licoreando</title>
</head>
<body class="index">
{% include 'header.html' %}
<div class ="titulo"><h1>Bienvenido a licoreando, tu web de licores</h1></div>
</body>
</html>

Licoreando/licor/templates/search_licor.html
<html>
<head>
<title>Licores</title>
</head>
<body>
<header>
{% include 'header.html' %}

<div class="search">
<h1>Buscar licores</h1>
<form id='form' method='post'>
{% csrf_token %}
{{form.as_p}}
<select multiple="multiple" name="categoria" >
{% for cat in categorias %}
  <option value="{{cat.id}}">{{cat.nombre}}</option>
 {%endfor%}
</select><br>
<a>Ordenar tabla por:</a><br>
<input type="radio" name="order" value="" checked="checked"> Similitud<br>
<input type="radio" name="order" value="precio"> Precio<br>
<input type="radio" name="order" value="titulo"> Título<br>
<input type="radio" name="order" value="graduacion"> Graduación<br>
<label>Mostrar: </label><input type="number" name="elem" value="{{elem}}"><br>
<label>Página: </label><input type="number" name="page" value="{{page}}"><br>
<a>Seleccione el número de elementos a mostrar</a><br>
<a>Seleccione la página que ver</a><br>
<p><input type='submit' value='Buscar'/></p>
</form>
</div>

<table style="width:50%" align="center" >
  <tr>
    <th>Título</th>
	<th>Imagen</th>
    <th>Código</th> 
    <th>Descripción</th>
    <th>Precio</th>
    <th>Origen</th> 
    <th>Cantidad/Peso</th>
    <th>Graduación</th>
    <th>Categoría</th>
    <th>Enlace</th>
    <th>Stock</th>
  </tr>
{% for licor in licores %}
  <tr>
    <td>{{licor.titulo}}</td>
    <td><img src="{{licor.urlImagen}}" width="100px"/></td> 
    <td>
    {% if not licor.codigoReferencia == "" %}
    	{{licor.codigoReferencia}}</td>
    {%endif%}
    {% if licor.codigoReferencia == "" %}
    	---
    {%endif%}
    </td> 
    <td><div class="tooltip">
    {%if not licor.descripcion == "" %}
        <a class="description">Descripción</a><span class="tooltiptext">{{licor.descripcion}}</span></div>
    {%endif%}
    {%if licor.descripcion == "" %}
        <a>---</a>
    {%endif%}
  </td>
    <td>
    {% if not licor.precio == "" %}
    	{{licor.precio}}€
    {%endif%}
    {% if licor.precio == "" %}
    	Desconocido
    {%endif%}
    </td>
    <td>
    {% if not licor.origen == "" %}
    	{{licor.origen}}
    {%endif%}
    {% if licor.origen == "" or licor.origen == "Desconocido" %}
    	No disponible
    {%endif%}
    </td> 
    <td>
    {% if not licor.cantidad == "" %}
    	{{licor.cantidad}}
    {%endif%}
    {% if licor.cantidad == "" %}
    	No disponible
    {%endif%}
    </td>
    <td>
    {% if not licor.graduacion == "" %}
    	{{licor.graduacion}}º
    {%endif%}
    {% if licor.graduacion == "" %}
    	No disponible
    {%endif%}
    </td>
    <td>
    {% for cate in licor.categoria_set.all %}
    <p>{{cate.nombre}}</p>
    {% endfor %}
    </td>
    <td><a href="{{licor.urlProducto}}" target="_blank">Enlace</a></td>
    {% if licor.enStock == True %}
    	<td><a class="green">En stock</a></td>
    {%endif%}
    {% if licor.enStock == False %}
    	<td><a class="red">Sin stock</a></td>
    {%endif%}
 </tr>
{% endfor %}
</table>
</body>
</html>